-- MariaDB queries
-- Create mock DWH db (snowflake schema)
DROP DATABASE IF EXISTS `DWH`;

CREATE DATABASE `DWH`;

USE `DWH`;

DROP TABLE IF EXISTS `SALES_FACT`;
DROP TABLE IF EXISTS `PERMISSIONS_DIM`;
DROP TABLE IF EXISTS `DEPARTMENTS_DIM`;
DROP TABLE IF EXISTS `OUTLETS_DIM`;
DROP TABLE IF EXISTS `PRODUCTS_DIM`;
DROP TABLE IF EXISTS `TIMES_DIM`;

CREATE TABLE `OUTLETS_DIM` (
	`OUTLET_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`OUTLET_NAME` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`ADDRESS` VARCHAR(200) NOT NULL COLLATE 'utf8mb4_general_ci',
	`PHONE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`OUTLET_NO`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

CREATE TABLE `PRODUCTS_DIM` (
	`ITEM_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`LINE_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`CLASS_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`ITEM_NAME` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`BARCODE` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ITEM_NO`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

CREATE TABLE `TIMES_DIM` (
	`SALES_NO` INT(10) UNSIGNED NOT NULL,
	`DAY` DATE NOT NULL,
	`WEEK` INT(10) UNSIGNED NOT NULL,
	`MONTH` CHAR(5) NOT NULL COLLATE 'utf8mb4_general_ci',
	`QUARTER` VARCHAR(10) NOT NULL COLLATE 'utf8mb4_general_ci',
	`YEAR` YEAR NOT NULL,
	PRIMARY KEY (`SALES_NO`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

CREATE TABLE `DEPARTMENTS_DIM` (
	`DEPT_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`DEPT_NAME` VARCHAR(100) NOT NULL COLLATE 'utf8mb4_general_ci',
	`DEPT_CODE` CHAR(3) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`DEPT_NO`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

CREATE TABLE `PERMISSIONS_DIM` (
	`ROLE_NO` INT(10) UNSIGNED NOT NULL,
	`DEPT` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`IN_CHARGE_OF` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`ROLE_NO`) USING BTREE,
	INDEX `FK_PermissionsDim_DepartmentsDim` (`DEPT`) USING BTREE,
	INDEX `FK_PermissionsDim_OutletsDim` (`IN_CHARGE_OF`) USING BTREE,
	CONSTRAINT `FK_PermissionsDim_DepartmentsDim` FOREIGN KEY (`DEPT`) REFERENCES `DWH`.`DEPARTMENTS_DIM` (`DEPT_NO`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK_PermissionsDim_OutletsDim` FOREIGN KEY (`IN_CHARGE_OF`) REFERENCES `DWH`.`OUTLETS_DIM` (`OUTLET_NO`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;

CREATE TABLE `SALES_FACT` (
	`SALES_NO` INT(10) UNSIGNED NOT NULL,
	`OUTLET_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`ITEM_NO` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`QUANTITY` INT(10) UNSIGNED NOT NULL,
	`UNIT_PRICE` DECIMAL(5,2) UNSIGNED NULL DEFAULT NULL,
	`REVENUE` DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (`SALES_NO`, `OUTLET_NO`, `ITEM_NO`) USING BTREE,
	INDEX `FK_SalesFact_TimesDim` (`SALES_NO`) USING BTREE,
	INDEX `FK_SalesFact_OutlesDim` (`OUTLET_NO`) USING BTREE,
	INDEX `FK_SalesFact_ProductsDim` (`ITEM_NO`) USING BTREE,
	CONSTRAINT `FK_SalesFact_TimesDim` FOREIGN KEY (`SALES_NO`) REFERENCES `DWH`.`TIMES_DIM` (`SALES_NO`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `FK_SalesFact_OutlesDim` FOREIGN KEY (`OUTLET_NO`) REFERENCES `DWH`.`OUTLETS_DIM` (`OUTLET_NO`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `FK_SalesFact_ProductsDim` FOREIGN KEY (`ITEM_NO`) REFERENCES `DWH`.`PRODUCTS_DIM` (`ITEM_NO`) ON UPDATE CASCADE ON DELETE NO ACTION
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB;
